---
- hosts: localhost

  vars:
    http_port: 8081
    domain: example.com

  tasks:

    - name: install packages
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - apache2

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

    - name: apache2 listen on port {{ http_port }}
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen " line="Listen {{ http_port }}" state=present
      notify:
        - restart apache2

    - name: apache2 virtualhost on port {{ http_port }}
      lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:" line="<VirtualHost *:{{ http_port }}>"
      notify:
        - restart apache2

    - name: get template virtual host file template
      get_url:
        url: https://raw.githubusercontent.com/ianalderman/holansiblepull/master/virtualhost.conf
        dest: /tmp/virtualhost.conf

    - name: create virtual host file from template
      template: src=/tmp/virtualhost.conf dest=/etc/apache2/sites-available/{{ domain }}.conf

    - name: a2ensite {{ domain }}
      command: a2ensite {{ domain }}
      args:
        creates: /etc/apache2/sites-enabled/{{ domain }}.conf
      notify:
        - restart apache2

    - name: clone basic html template
      git: repo=https://github.com/ianalderman/helloworldhtml.git dest=/var/www/html update=no

    - name: clear default site
      command: mv /etc/apache2/sites-enabled/000-default.conf /etc/apache2/sites-enabled/000-default.conf.old
      notify:
        - restart apache2
        
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted